name: Publish

on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest
    environment:
      name: main
    steps:
      - uses: actions/checkout@v2

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9
        with:
          versionSpec: '5.x'

      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v0.9
      
      - run: |
          echo "NuGetVersionV2: ${{ steps.gitversion.outputs.nuGetVersionV2 }}"
          echo "NuGetPreReleaseTagV2: ${{ steps.gitversion.outputs.CommitsSinceVersionSourcePadded }}"
    
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100

      - name: tests
        run: dotnet test -c Release --logger trx --results-directory out-tests
      
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
            name: test run
            path: out-tests/*.trx    
            reporter: dotnet-trx
            fail-on-error: 'true'

      - name: pack
        if: success()
        run: dotnet pack .\Minio.Client\Minio.Client.csproj -c Release -o out -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }}-${{ steps.gitversion.outputs.CommitsSinceVersionSourcePadded }} --include-symbols --include-source
      
      - name: publush
        if: success()
        run: dotnet nuget push .\out\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_ACCESS_TOKEN}} --skip-duplicate
     
