name: Publish

on:
  release:
    types: [published]

jobs:
  test:
    name: run tests
    runs-on: windows-latest
    environment:
      name: main
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: tests
        run: dotnet test .\Minio.Client.Test\Minio.Client.Test.csproj -c Release --logger trx --results-directory out-tests
      
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
            name: test run
            path: out-tests/*.trx    
            reporter: dotnet-trx
            fail-on-error: 'true'
            
  publish:
    needs: [test]
    if: success()
    name: build, pack & publish
    runs-on: ubuntu-latest
    environment:
      name: main
    steps:
      - uses: actions/checkout@v2
      
      - name: Package | Release
        id: release
        uses: tenhaus/get-release-or-tag@v2
          
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      
      - name: Package | Publish
        uses: drusellers/publish-nuget@v3
        with:
          project-file-path: ./Minio.Client/Minio.Client.csproj
          version: ${{ steps.release.outputs.tag }}
          nuget-key: ${{ secrets.NUGET_ACCESS_TOKEN }}
          include-symbols: true
