name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest
    environment:
      name: main
    steps:
      - uses: actions/checkout@v2
      
      - name: Package | Release
        id: release
        uses: tenhaus/get-release-or-tag@v2
          
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      
      - name: Package | Publish
        uses: drusellers/publish-nuget@v3
        with:
          project-file-path: .\Minio.Client\Minio.Client.csproj
          version: ${{ steps.release.outputs.tag }}
          tag-format: '*'
          nuget-key: ${{ secrets.NUGET_ACCESS_TOKEN }}
          include-symbols: true
