name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest
    environment:
      name: main
    steps:
      - uses: actions/checkout@v2
         
      - run: |
          set ref=%package_version:v=%
          echo %ref%
        env:
          package_version: ${{github.event.release.tag_name}}
          
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100

      - name: pack
        if: success()
        run: dotnet pack .\Minio.Client\Minio.Client.csproj -c Release -o out  -p:PackageVersion=$ref --include-symbols --include-source
      
      - name: publush
        if: success()
        run: dotnet nuget push .\out\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_ACCESS_TOKEN}} --skip-duplicate
     
