name: Publish

on:
  release:
    types: [published]

jobs:            
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    environment:
      name: main
    steps:
      - uses: actions/checkout@v2
          
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      
      - name: pack-http-client
        run: dotnet pack ./Minio.Client.Http/Minio.Client.Http.csproj -c Release -o out --include-symbols --include-source
  
      - name: publish-http-client
        run: dotnet nuget push ./out/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_ACCESS_TOKEN}} --skip-duplicate

      - name: pack-http-client-extensions
        run: dotnet pack ./Minio.Client.Http.DependencyInjection/Minio.Client.Http.DependencyInjection.csproj -c Release -o out-extensions --include-symbols --include-source
  
      - name: publish-http-client-extensions
        run: dotnet nuget push ./out-extensions/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_ACCESS_TOKEN}} --skip-duplicate
